/**
 * GENERATED by scripts/prepare-uttamkumar.mjs. Do not edit by hand.
 *
 * Pulled out of films.generated.ts (a ~28KB file) because
 * src/data/seo.ts reaches these two numbers eagerly, from every page, and
 * should not pull in all 211 rows to do it — the same reasoning
 * kabirsuman/counts.generated.ts gives for the same split.
 */
export const TOTAL_FILMS = 211;
export const FIRST_YEAR = 1948;
export const LATEST_YEAR = 2024;
