/**
 * Writes src/data/lastmod.ts, the real last-modified date of each page.
 *
 * `<lastmod>` is the only sitemap field Google still reads (it dropped
 * `changefreq` and `priority` years ago), and it reads it *conditionally*: a
 * lastmod that does not match what actually changed teaches it to ignore the
 * sitemap. So the date is taken from git rather than invented — the newest
 * commit touching any file that decides what a given route says.
 *
 * This script only *writes* TypeScript, it never imports it. That keeps it a
 * plain .mjs with no loader, no transpiler and no dependency, while the
 * generated module is imported normally by functions/sitemap.xml.ts.
 *
 * Runs automatically via the `prebuild` npm hook.
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

/**
 * What each page's content actually depends on. `seo.ts` holds its copy and
 * `prerender.ts` the markup a crawler is served; beyond that the front page
 * is the catalogue, and the bus page is its scene and its playlists. A change
 * to any of them is a change to the page.
 */
const SHARED = ["src/data/seo.ts", "src/lib/prerender.ts"];

const TARAKESWAR_SHARED = [
  "src/data/tarakeswar/core.ts",
  "src/data/tarakeswar/jsonld.ts",
  "src/data/tarakeswar/prerender.ts",
  "src/components/tarakeswar/TarakeswarLayout.tsx",
  "src/components/tarakeswar/shared.tsx",
];

const PAGES = {
  home: [...SHARED, "src/data/experiences.ts", "src/pages/HomePage.tsx"],
  busdriver: [...SHARED, "src/data/scene.ts", "src/data/playlists.ts", "src/components/RoadScene.tsx"],
  mahalaya: [...SHARED, "src/data/broadcast.ts", "src/pages/MahalayaPage.tsx", "src/components/DawnScene.tsx"],
  tarakeswar: [...SHARED, ...TARAKESWAR_SHARED, "src/pages/tarakeswar/TarakeswarHubPage.tsx"],
  tarakeswarTemple: [...SHARED, ...TARAKESWAR_SHARED, "src/pages/tarakeswar/TarakeswarTemplePage.tsx"],
  tarakeswarFood: [
    ...SHARED,
    ...TARAKESWAR_SHARED,
    "src/data/tarakeswar/directory.ts",
    "src/pages/tarakeswar/TarakeswarFoodPage.tsx",
  ],
  tarakeswarReach: [...SHARED, ...TARAKESWAR_SHARED, "src/pages/tarakeswar/TarakeswarReachPage.tsx"],
  // The blog index's own lastmod; individual posts carry their own
  // publishedDate/updatedDate in src/data/tarakeswar/blog.ts instead of a
  // git-derived one, since sitemap.xml.ts reads those directly.
  tarakeswarBlog: [
    ...SHARED,
    ...TARAKESWAR_SHARED,
    "src/data/tarakeswar/blog.ts",
    "src/pages/tarakeswar/TarakeswarBlogIndexPage.tsx",
  ],
};

/** ISO-8601 date of the newest commit touching any of `files`, or null. */
function lastCommitDate(files) {
  try {
    const out = execFileSync("git", ["log", "-1", "--format=%cI", "--", ...files], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    return out || null;
  } catch {
    return null; // no git, or no history for these paths
  }
}

const dates = Object.fromEntries(
  Object.entries(PAGES).map(([id, files]) => [id, lastCommitDate(files)]),
);

const missing = Object.entries(dates).filter(([, d]) => !d).map(([id]) => id);
if (missing.length) {
  // A shallow clone (Cloudflare Pages does depth-1 by default) has no history
  // to read, so the honest result is no date at all. sitemap.xml omits the
  // element entirely rather than stamping "now" on pages that did not change.
  console.warn(`[stamp-lastmod] no git date for: ${missing.join(", ")} — lastmod omitted`);
}

const body = `// GENERATED by scripts/stamp-lastmod.mjs. Do not edit, do not commit.
// Last-modified date per page, read from git at build time. null means the
// build had no history to read (a shallow clone), in which case the sitemap
// omits <lastmod> rather than asserting a date it cannot support.
import type { PageId } from "./seo";

export const LAST_MODIFIED: Record<PageId, string | null> = ${JSON.stringify(dates, null, 2)};
`;

writeFileSync(new URL("../src/data/lastmod.ts", import.meta.url), body);
console.log("[stamp-lastmod] wrote src/data/lastmod.ts");
