// Generated by scripts/prepare-suman.mjs. Do not edit by hand.
// A handful of plain-literal counts, split out from catalogue.generated.ts
// so that src/data/kabirsuman/seo.ts — reached eagerly from every page via
// src/data/seo.ts — can quote them without pulling the ~160KB catalogue
// (all 30 albums and 317 songs) into the main JS bundle. See
// src/App.tsx's lazy-loaded Kabir Suman routes for the other half of this.
export const TOTAL_ALBUMS = 30;
export const TOTAL_SONGS = 317;
export const FIRST_YEAR = 1992;
export const LATEST_YEAR = 2014;
