// GENERATED by scripts/prepare-mahalaya.mjs. Do not edit by hand.
//
// Measured off the delivered art: the room's window opening after the painted
// checkerboard was keyed out, and each layer's aspect. The scene lays the sky,
// the sun and the city inside `window`, then the room on top masks the rest.

export const MAHALAYA_VERSION = "eee14f2d";

export const MAHALAYA_GEOMETRY = {
  roomAspect: 1.7768,
  /** the window opening, as fractions of the room image */
  window: { left: 0.3373, top: 0.2465, right: 0.5748, bottom: 0.8874 },
  radioAspect: 1.4945,
  maaAspect: 3.1461,
  layers: {
    "maha-clouds": 1.7768,
    "maha-city-far": 2.5006,
    "maha-city-near": 2.5006,
    "maha-curtain": 0.6667,
  },
} as const;
